
name: CI

on:
  push

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src'   # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'build'
      shell: bash 
      run: dotnet build 
    
    - name: 'test'
      shell: bash 
      run: |
        pushd tests 
        dotnet test
